### ISSUE TITLE
BlockNotFound crash

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-exporter#1]
When BlockNotFound comes up it crashes the exporter, and it has to be manually restarted. 
![yearn exporter crash](https://user-images.githubusercontent.com/38810205/98434379-e710eb00-2109-11eb-9713-0925b147b535.png)

**Comment by banteg** [comment]
Seems like a problem with load balancing between several nodes.

Should be fixable with a height buffer, so it lags by a few blocks.

**Comment by DarkGhost7** [comment]
Mostly fixed on the newest updates but I still occasionally see this on v1 exporter.
