### ISSUE TITLE
Does not pull strategies with the same name

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-exporter#101]
![image](https://user-images.githubusercontent.com/38810205/126880147-883c9261-cfee-4c43-b853-f26613b080d8.png)
This can be seen if you try to view yvsUSD 3.3 vault's strategies, it only has one `SingleSidedCrvsUSD` when in fact there are two.

**Comment by milkyklim** [comment]
Is resolved as per @BobTheBuidler

**Comment by BobTheBuidler** [comment]
@DarkGhost7 can you confirm you've only seen this impact v2 vaults?

**Comment by BobTheBuidler** [comment]
I've confirmed that vault.strategies contains the missing strat but vault.describe() does not. Proceeding to investigate
![image](https://user-images.githubusercontent.com/70677534/135549001-70d0e734-119f-4165-bf54-1465d4c89e0f.png)

**Comment by BobTheBuidler** [comment]
PR #135 fixes this
added a handler to Vault class that appends '(2)' to the end of the 2nd instance of the same name and increments upward for each additional instance

**Comment by BobTheBuidler** [comment]
example output: 
![image](https://user-images.githubusercontent.com/70677534/135550207-20313954-b5e2-4edc-86c2-a1fb59e45859.png)
