### ISSUE TITLE
count Ribbon's yvUSDC in Opyn

### ISSUE THREAD

**Issue by 0x7171** [yearn/yearn-exporter#174]
![IMAGE 2021-12-03 12:01:47](https://user-images.githubusercontent.com/91192250/144642692-f702a228-9ccf-4bf6-90f1-da9ae28586e7.jpg)

0xJiji, [15 Nov 2021, 05:22:59 (15 Nov 2021, 05:17:40)]:
yvUSDC Theta Vault address: 0x8FE74471F198E426e96bE65f40EeD1F8BA96e54f

Lookup from Opyn Controller: https://etherscan.io/address/0x4ccc2339F87F6c59c6893E1A678c2266cA58dC72#readProxyContract

1. First, call the accountVaultCounter function accountVaultCounter(0x8FE74471F198E426e96bE65f40EeD1F8BA96e54f)
2. Then call the getVault function getVault(0x8FE74471F198E426e96bE65f40EeD1F8BA96e54f, 20)
3. The deposited yvUSDC amount is the last number in the tuple

Relevant telegram thread: https://t.me/c/1410227556/4218

**Comment by tallywiesenberg** [comment]
@DarkGhost7 hey, is this free to claim? Seems to be a few contract read calls. im happy to help.
