### ISSUE TITLE
Runs to fast for a free infura account

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-exporter#2]
Running it at its current speed will use up a free 100k requests infura account in a few hours.

**Comment by banteg** [comment]
This is known, optimizing it to work with Infura would require a bit more than adding a sleep after each iteration.

I will address this by batching calls using multicall and adding an optional sleep interval.

**Comment by mariuspod** [comment]
I think we've addressed it by using `multicall` and applying a sleep interval via env variable `SLEEP_SECONDS`
