### ISSUE TITLE
[WEB-1256-201] clarify how ib tvl is calculated

### ISSUE THREAD

**Issue by banteg** [yearn/yearn-exporter#201]
[https://github.com/yearn/yearn-exporter/blob/aa6f8a1b9f568454bbe9edcae2712c006f3d1056/yearn/ironbank.py#L106](https://github.com/yearn/yearn-exporter/blob/aa6f8a1b9f568454bbe9edcae2712c006f3d1056/yearn/ironbank.py#L106)

it's currently `cash + borrowed - reserves`

**Comment by 0xkofee** [comment]
@banteg can this be closed since pr 199 is merged?

**Comment by DarkGhost7** [comment]
Was this fixed though in #199? Ib is still running just not shown for tvl purposes, might be very low priority though.
