### ISSUE TITLE
Make yearn.science tokenlist multichain

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-exporter#211]
"Hey guys, we use yearn.science for pulling supported tokens and [https://github.com/yearn/yearn-assets](https://github.com/yearn/yearn-assets) for images. I see that you've refactored the GitHub paths to be /multichain-tokens but yearn.science doesn't reflect that just yet"

**Comment by DarkGhost7** [comment]
Yes @Majorfi

**Comment by DarkGhost7** [comment]
Should be hosted here as well https://meta.yearn.finance/api/tokens/list

**Comment by 0xBasically** [comment]
in ydaemon now
