### ISSUE TITLE
[EXP-19-220] Create API endpoint for fetching prices

### ISSUE THREAD

**Issue by mariuspod** [yearn/yearn-exporter#220]
> it should accept an array of tokens, and return token prices for each, ideally in the format \[{"address": "0x...", "priceUsdc: ..."}\]

**Comment by 0xkofee** [comment]
@mariuspod since this issue was opened by you and self assigned, does that mean you are working on it?

**Comment by mariuspod** [comment]
linear auto-closed it as I just linked it with this PR: https://github.com/yearn/yearn-exporter/pull/229
