### ISSUE TITLE
[EXP-27-227] add support for gnosis chain

### ISSUE THREAD

**Issue by banteg** [yearn/yearn-exporter#227]
add minimal support for gnosis chain since we are contemplating deploying there.

* add to networks
* update oracles
* vault registry

**Comment by banteg** [comment]
gdaddy safe:
https://gnosis-safe.io/app/gno:0x22eAe41c7Da367b9a15e942EB6227DF849Bb498C/balances

registry deployed:
0xe2F12ebBa58CAf63fcFc0e8ab5A61b145bBA3462

yvUSDC: 0x21d7b09bcf08f7b6b872bed56cb32416ae70bcc8

**Comment by 0xkofee** [comment]
I'll see if I can figure it out

**Comment by 0xkofee** [comment]
WIP https://github.com/yearn/yearn-exporter/pull/239
Will try to run some of these scripts later tonight

**Comment by BobTheBuidler** [comment]
PR #239  has been closed and replaced with #289

**Comment by BobTheBuidler** [comment]
Closing this as #289  has been merged
