### ISSUE TITLE
[EXP-52-252] Malformed token errors breaking historical exporters

### ISSUE THREAD

**Issue by mariuspod** [yearn/yearn-exporter#252]
# FTM

`could not fetch price for malformed token 0x58e57cA18B7A47112b877E31929798Cd3D703b0f on Fantom at 27501504`\
[https://sentry.yearn.vision/organizations/yearn/issues/534/?environment=staging&project=2](https://sentry.yearn.vision/organizations/yearn/issues/534/?environment=staging&project=2)

reproduce with brownie:
```
from yearn.prices import magic
magic.get_price('0x58e57cA18B7A47112b877E31929798Cd3D703b0f', block=27501504)
```

# ETH

`failed to get price for malformed token 0xEd4064f376cB8d68F770FB1Ff088a3d0F3FF5c4d on Mainnet at 13967922`\
[https://sentry.yearn.vision/organizations/yearn/issues/651/?environment=staging&project=2](https://sentry.yearn.vision/organizations/yearn/issues/651/?environment=staging&project=2)

reproduce with brownie:
```
from yearn.prices import magic
magic.get_price('0xEd4064f376cB8d68F770FB1Ff088a3d0F3FF5c4d', block=13967922)
```

**Comment by 0xkofee** [comment]
This worked for me on eth using alchemy @mariuspod 
```
magic.get_price('0xEd4064f376cB8d68F770FB1Ff088a3d0F3FF5c4d', block=13967922)
611.0582155639148
```

**Comment by mariuspod** [comment]
@0xkofee thanks for verifying and letting me know!
I can't reproduce it anymore either for both cases, I think @BobTheBuidler has worked on the resolution of this.
