### ISSUE TITLE
[EXP-71-271] Inaccurate price for Rocketpool WSTETH LPs

### ISSUE THREAD

**Issue by wavey0x** [yearn/yearn-exporter#271]
In this transaction, we can see that 1 curve LP for the rocketpool wsteth pool is valued near 1 wsteth.\
[https://etherscan.io/tx/0x7684daf36307027d2c724b1349d62a36428be75cafa8d9badc8085cb3338b768](https://etherscan.io/tx/0x7684daf36307027d2c724b1349d62a36428be75cafa8d9badc8085cb3338b768)

In yearn exporter, we have an inaccurate price returned when querying for the price of this same LP. We get $0.066 when it should be closer to $2,900.

![](https://uploads.linear.app/71c58dc2-224e-40a9-b4c0-5ae717f1e931/2558758f-e861-4f4c-883b-f2e149443e02/0a467a05-75f8-410e-b474-018d41d6078b)

**Comment by dudesahn** [comment]
Issue is described in #272
