### ISSUE TITLE
Current version is incompatible with docker-compose 2.x.x

### ISSUE THREAD

**Issue by BobTheBuidler** [yearn/yearn-exporter#360]
from Zack in YFI Exporter chat: "1.29 version works. I was using version 2.3 that was provided by docker desktop(I believe), so tried pip install docker-compose which installed 1.29. The current Makefile does not seem to be compatible for v2."

**Comment by murderteeth** [comment]
fwiw, compose-switch worked for me, https://github.com/docker/compose-switch

**Comment by mariuspod** [comment]
this is already fixed in master
