### ISSUE TITLE
bug: endpoint not working

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-exporter#629]
This endpoint is not working: https://api.yexporter.io/v1/chains/10/vaults/all
<img width="1501" alt="Screenshot 2023-09-21 at 14 49 53" src="https://github.com/yearn/yearn-exporter/assets/839844/45742206-7a9a-4f86-a4d7-1590972052be">

**Comment by pmdaly** [comment]
@saltyfacu can we close this issue? looks like the endpoint works now.

**Comment by saltyfacu** [comment]
It's a month old. If it is, yes
