### ISSUE TITLE
nginx-prometheus-exporter can not start nginx client

### ISSUE THREAD

**Issue by leonboripgs** [yearn/yearn-exporter#89]
Hi
I was trying to run the yearn-exporter on my Ubuntu but I am getting the error related to nginx client starting.
Here is my error message.

 2021/07/13 19:02:23 Could not create Nginx Client: expected 200 response, got 404

Is there any additional settings to be customized in prometheus?
Thanks.

**Comment by mariuspod** [comment]
hi @leonboripgs 
the nginx exporter has been removed by d61f78bd860394463d2e50747b957609227f148a

git pull and rebuilding should fix it :-)
